development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: game_translator_development
  pool: 5
  username: root

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: game_translator_test
  pool: 5
  username: root