development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: game_translator_development
  pool: 5
  username: root

click_jogos_development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: clickjogos_development
  pool: 5
  username: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: game_translator_test
  pool: 5
  username: root

click_jogos_test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: clickjogos_test
  pool: 5
  username: root