development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: users_development
  pool: 5
  username: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: users_test
  pool: 5
  username: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: users_production
  pool: 5
  username: root