# Afrikaans
- af
# Arabic
- ar
# Azerbaijani
- az
# Bulgarian
- bg
# Bengali
- bn
# Bosnian
- bs
# Catalan
- ca
# Czech
- cs
# Welsh
- cy
# Danish
- da
# German
- de
- de-AT
- de-CH
# Greek
- el
# English
- en
- en-AU
- en-CA
- en-GB
- en-IE
- en-IN
- en-NZ
# Esperanto
- eo
# Spanish
- es
- es-419
- es-AR
- es-CL
- es-CO
- es-MX
- es-PE
- es-VE
# Estonian
- et
# Basque
- eu
# Faeroese
- fa
# Finnish
- fi
# French
- fr
- fr-CA
- fr-CH
# Galician
- gl
# Hebrew
- he
# Hindi
- hi
- hi-IN
# Croatian
- hr
# Hungarian
- hu
# Indonesian
- id
# Icelandic
- is
# Italian
- it
- it-CH
# Japanese
- ja
# Kannada
- kn
# Korean
- ko
# Laothian
- lo
# Lithuanian
- lt
# Latvian
- lv
# Macedonian
- mk
# Mongolian
- mn
# Norwegian
- nb
# Nepalese
- ne
# Dutch
- nl
# Norwegian (Nynorsk)
- nn
# Oriya
- or
# Polish
- pl
# Portuguese (Brazil)
- pt-BR
# Portuguese (Portugal)
- pt
# Rhaeto-Romance
- rm
# Romanian
- ro
# Russian
- ru
# Slovak
- sk
# Slovenian
- sl
# Serbian
- sr
# Swedish
- sv
# Swahili (Kiswahili)
- sw
# Thai
- th
# Tagalog
- tl
# Turkish
- tr
# Ukrainian
- uk
# Uzbek
- uz
# Vietnamese
- vi
# Wolof
- wo
# Chinese
- zh-CN
- zh-HK
- zh-TW